# Generated by Django 3.2.8 on 2022-05-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_item', models.CharField(blank=True, help_text='Name of item', max_length=122, null=True)),
                ('image', models.ImageField(blank=True, help_text='Image of item', null=True, upload_to='')),
                ('category', models.CharField(blank=True, help_text='Category', max_length=22, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Amount paid for item', max_digits=50, null=True)),
                ('discounts', models.DecimalField(blank=True, decimal_places=2, help_text='Discount prince', max_digits=50, null=True)),
                ('platesize', models.CharField(blank=True, help_text='Size of item', max_length=50, null=True)),
            ],
        ),
    ]
