# Generated by Django 3.2.8 on 2022-05-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(blank=True, help_text='Image of item', null=True, upload_to='productimg'),
        ),
    ]
