name: Vulnerability Check

on:
  push:
    branches:
      - master

jobs:
  pip-audit:
  runs-on: ubuntu-latest

    steps:
      - uses: pypa/gh-action-pip-audit@v1.0.0
        with:
          inputs: requirements.txt
