name: Vulnerability Check

on:
  push:
    branches:
      - master

jobs:
  selftest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install
        run: |
          python -m venv env
          source env/bin/activate
          python -m pip install -r requirement.txt
      - uses: pypa/gh-action-pip-audit@v1.0.8
        with:
          virtual-environment: env
