name: Vulnerability Check

on:
  push:
    branches:
      - master

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      
      - name: Install safety
        run: pip install safety

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Check for vulnerabilities
        run: safety check --full-report
